"""initial migration

Revision ID: 65872c2abde8
Revises: 
Create Date: 2023-01-19 15:45:07.056117

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '65872c2abde8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_data',
    sa.Column('user_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('jobs',
    sa.Column('job_id', sa.String(), nullable=False),
    sa.Column('job_name', sa.String(), nullable=True),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user_data.user_id'], ),
    sa.PrimaryKeyConstraint('job_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobs')
    op.drop_table('user_data')
    # ### end Alembic commands ###
