"""V1.1

Revision ID: bffff6ba1fc1
Revises: 65872c2abde8
Create Date: 2023-01-19 16:15:11.737746

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bffff6ba1fc1'
down_revision = '65872c2abde8'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_name', sa.String(), nullable=True))
    op.drop_constraint('jobs_user_id_fkey', 'jobs', type_='foreignkey')
    op.drop_column('jobs', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('jobs_user_id_fkey', 'jobs', 'user_data', ['user_id'], ['user_id'])
    op.drop_column('jobs', 'user_name')
    # ### end Alembic commands ###
